name: Update Cobh iCal Feed

on:
  schedule:
    - cron: "17 6 * * *"   # daily at 06:17 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate ICS
        run: |
          python generate_cobh_ics.py

      - name: Commit and push if changed
        run: |
          git config user.name "cobh-ical-bot"
          git config user.email "cobh-ical-bot@users.noreply.github.com"
          git add cobh-cruise.ics
          git diff --cached --quiet || (git commit -m "Update cobh-cruise.ics" && git push)
